### ISSUE TITLE
Unable to see the sample Credential provider after installation

### ISSUE THREAD

**Issue by subu1979** [jamiehighfield/windowscredentialprovider#2]

**Comment by subu1979** [comment]
Finaly able to register and unregister (refer register_unregister.zip)

Also tested in ARM64


[register_unregister.zip](https://github.com/jamiehighfield/windowscredentialprovider/files/14973192/register_unregister.zip)

**Comment by jamiehighfield** [comment]
The `master` branch currently contains an older version of the library. I'm working on improvements slowly, but in the `net6-upgrade` branch. This should be a little easier to register. Make sure to compile for x64, x86, ARM, etc. (dependent on your processor architecture), and place it in the `system32` folder, and register using `regsvr32` (for the `net6-upgrade` branch).
